# Generated by Django 5.1.5 on 2025-01-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('BoatOwner', 'BoatOwner'), ('Manager', 'Manager'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
