# Generated by Django 5.1.5 on 2025-01-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
