# Generated by Django 5.1.5 on 2025-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0003_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
