# Generated by Django 5.1.5 on 2025-04-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_alter_boat_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='boat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='boats.boat'),
            preserve_default=False,
        ),
    ]
