# Generated by Django 5.1.5 on 2025-05-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_alter_booking_boat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='tour_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='boats.tourtype'),
        ),
    ]
