# Generated by Django 5.1.5 on 2025-05-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_alter_tourpackage_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='boat',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='boat',
            name='multiple_photos',
            field=models.ManyToManyField(blank=True, to='boats.photo'),
        ),
    ]
