# Generated by Django 5.1.5 on 2025-05-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0007_photo_boat_videos_boat_multiple_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='is_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabin',
            name='is_attached_belcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabin',
            name='is_attached_washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabin',
            name='is_non_ac',
            field=models.BooleanField(default=False),
        ),
    ]
