# Generated by Django 5.1.5 on 2025-05-12 19:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0008_cabin_is_ac_cabin_is_attached_belcony_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tourpackageschedule',
            options={'ordering': ['start_date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='tourpackageschedule',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='tourpackageschedule',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='tourpackageschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackageschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackageschedule',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tourpackageschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='cabin_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packages', to='boats.user'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_packages', to='boats.user'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='guest_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='guest_limitation',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_packages', to='boats.user'),
        ),
        migrations.AlterField(
            model_name='tourpackageschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to='boats.user'),
        ),
        migrations.AlterField(
            model_name='tourpackageschedule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_schedules', to='boats.user'),
        ),
        migrations.AlterField(
            model_name='tourpackageschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedules', to='boats.user'),
        ),
    ]
