# Generated by Django 5.1.5 on 2025-05-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0009_alter_tourpackage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='booked_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
