# Generated by Django 5.1.5 on 2025-05-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0010_alter_tourpackage_booked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackageschedule',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackageschedule',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackageschedule',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
