# Generated by Django 5.1.5 on 2025-05-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_alter_tourpackage_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackageschedule',
            name='package',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tour_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='boats.tourpackageschedule'),
        ),
    ]
