# Generated by Django 5.1.5 on 2025-05-12 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0012_remove_tourpackageschedule_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackageschedule',
            name='package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='boats.tourpackage'),
            preserve_default=False,
        ),
    ]
