# Generated by Django 5.1.5 on 2025-05-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0013_tourpackageschedule_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='boats.photo'),
        ),
    ]
